name: Label issue

on:
  issues:
    types: [opened, reopened]

jobs:
  label:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Parse issue body
      id: issue-parser
      uses: edumserrano/github-issue-forms-parser@f4e7864950f591c91ddd5215592484a4c789cebd
      continue-on-error: true
      with:
        template-filepath: '.github/ISSUE_TEMPLATE/bugreport.yml'
        issue-form-body: '${{ github.event.issue.body }}'

    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        cache: 'pip'
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Label issue
      run: ./label.py
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_BODY: ${{ steps.issue-parser.outputs.parsed-issue }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
